// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnzcynuehkxbkfljaydx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduemN5bnVlaGt4YmtmbGpheWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzI3MzAsImV4cCI6MjA2OTcwODczMH0.XQJX1hsdpEp3p5Bg14I6e-m7pZEYmTND3qNoGSd28aU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});